name: pr-check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Install node
        uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Install safe-chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/download/1.4.2/install-safe-chain.sh | sh -s -- --ci

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build library
        run: yarn build
        working-directory: ./packages/lib

      - name: Test library
        run: yarn test:coverage
        working-directory: ./packages/lib

      - name: Build docs
        run: yarn build
        working-directory: ./packages/docs
